name: Talk Proposal
description: Create a proposal for your talk at FOSSC Weekly Open-Mic Sessions. 
labels: ["proposal"]
assignees:
  - akshatcoder-hash
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Please share the title of your talk
      placeholder: For E.g, Blockchain 101
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe your Talk
      description: Brief description about your talk in 50-100 words.
    validations:
      required: true
  - type: textarea
    id: prerequisites
    attributes:
      label: Pre-requisites & reading material
      description: Anything that needs to be distributed or shared before the session starts
  - type: input
    id: time
    attributes:
      label: Time required for the talk 
      description: Please specify how much time does your talk requires (E.g 30 mins, 45 mins etc)
    validations:
      required: true
  - type: input
    id: slides
    attributes:
      label: Link to slides/demos
      description: How can we get in touch with you if we need more info?
      placeholder: ex. https://slides.com/....
      render: link
    validations:
      required: false
  - type: textarea
    id: about-author
    attributes:
      label: About you
      description: Briefly describe who you are and what you do. Include your socials like Twitter, Facebook.
    validations:
      required: true
  - type: input
    id: availability
    attributes:
      label: Availability
      description: When would you be able to give this talk?
      placeholder: DD/MM/YYYY
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: Any comments
      description: Share any other information that you think is necessary
    validations:
      required: false

